import matplotlib.pyplot as pyplot
import numpy as num
fs=int(input("enter the sampling frequency"))
f1=int(input("enter the first frequency"))
f2=int(input("enter the second frequency"))
n=int(input("enter the sample rate"))
x=num.arange(n)
x1=num.cos(2*num.pi*f1/fs*x)
pyplot.subplot(4,1,1)
pyplot.plot(x,x1)
pyplot.title('cos1')
pyplot.xlabel('---->samples')
pyplot.ylabel('---->amplitude')
x2=num.cos(2*num.pi*f2/fs*x)
pyplot.subplot(4,1,2)
pyplot.plot(x,x2)
pyplot.title('cos2')
pyplot.xlabel('---->samples')
pyplot.ylabel('---->amplitude')
y=x1+x2
pyplot.subplot(4,1,3)
pyplot.plot(x,y)
pyplot.title('sampled output')
pyplot.show( )
